# Generated by Django 3.1.7 on 2021-03-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description here'),
        ),
    ]
